### PR TITLE
Fix/apply transforms

### PR DESCRIPTION
**Pull request by DavidMerzJr**
The transform to the ellipsoid is not currently applied when the mesh is generated.  This PR applies the transform (both rotation and translation) before sending the ellipsoid to the mesh exporter.

### CODE REVIEW

**Comment by DavidMerzJr** [comment]
This should address Issue #3.

**Review by mpowelson — COMMENTED** [review]
Did you mean to leave those print statements in there? Also, do we really need scipy (Or do we already use it somewhere else)? It seems like it would be easy enough to just loop over the vertices and apply the transformation.

**Comment by DavidMerzJr** [comment]
I did not mean to leave those print statements in, but they flew under the radar because they do not show up when using roslaunch.  I'll pull them out.

The TF lookup is returning a quaternion and a translation vector, not a transformation matrix.  I could not find a built-in transform object/wrapper in numpy - scipy seems to be the way to handle them.  If we manually built the rotation matrix (or manually implemented the quaternion math), we could iterate over and apply to each vertex, but it would be much slower.  If we did go that route, it would probably still be more efficient to multiply the 3x3 rotation times the 3xN matrix of transposed vertices.

**Comment by mpowelson** [comment]
> I did not mean to leave those print statements in, but they flew under the radar because they do not show up when using roslaunch. I'll pull them out.
> 
> The TF lookup is returning a quaternion and a translation vector, not a transformation matrix. I could not find a built-in transform object/wrapper in numpy - scipy seems to be the way to handle them. If we manually built the rotation matrix (or manually implemented the quaternion math), we could iterate over and apply to each vertex, but it would be much slower. If we did go that route, it would probably still be more efficient to multiply the 3x3 rotation times the 3xN matrix of transposed vertices.

I thought TF had some utilities for converting to rotation matrices. Then we could just multiply them like you say. I'm not that upset by having scipy in there. We just need to make sure it's setup correctly so rosdep will pull it. I'm not sure how you're supposed to do that in Python. A quick google says maybe just add python-scipy to the package.xml run_depends

**Comment by DavidMerzJr** [comment]
It looks like tf exports an unrelated python module called transformations.py, which can be used to perform this conversion.  I'll switch over to that.

**Comment by DavidMerzJr** [comment]
I have switched from using scipy to the transformations.py imported by tf.  The rotation and translation are now performed by one matrix multiplication.

And I think I even managed to do it without adding unnecessary print statements.

**Comment by mpowelson** [comment]
I like it. Thanks

**Pull request merged**
